#!/bin/bash


defaults write /Library/Preferences/com.apple.HIToolbox '{
    AppleCurrentKeyboardLayoutInputSourceID = "com.apple.keylayout.Swedish-Pro";
    AppleInputSourceHistory =     (
                {
            InputSourceKind = "Keyboard Layout";
            "KeyboardLayout ID" = 7;
            "KeyboardLayout Name" = "Swedish - Pro";
        }
    );
    AppleSelectedInputSources =     (
                {
            InputSourceKind = "Keyboard Layout";
            "KeyboardLayout ID" = 7;
            "KeyboardLayout Name" = "Swedish - Pro";
        }
    );
}'


exit 0
